# Generated by Django 5.1.7 on 2025-08-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fieldtype_customuser_created_at_and_more'),
    ]

    operations = [
    ]
