# Generated by Django 5.1.7 on 2025-08-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20250806_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dynamicform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='is_public',
            field=models.BooleanField(default=False, help_text='¿Puede ser llenado por usuarios no registrados?'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('spend', 'Gasto'), ('earn', 'Ganancia'), ('admin_grant', 'Otorgado por Admin'), ('refund', 'Reembolso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Es usuario administrador'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Organización')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug único')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.IntegerField(default=10, verbose_name='Máximo de usuarios')),
                ('max_forms', models.IntegerField(default=50, verbose_name='Máximo de formularios')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_organization', 'Crear Organización'), ('create_form', 'Crear Formulario'), ('edit_form', 'Editar Formulario'), ('delete_form', 'Eliminar Formulario'), ('add_field', 'Agregar Campo'), ('remove_field', 'Eliminar Campo'), ('invite_user', 'Invitar Usuario'), ('change_role', 'Cambiar Rol'), ('submit_form', 'Enviar Formulario'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.dynamicform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='mainapp.organization')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.organization'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='mainapp.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador'), ('form_filler', 'Llenador de Formularios')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mainapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
