# Generated by Django 5.1.7 on 2025-08-06 21:56

from django.db import migrations
from django.utils.text import slugify


def create_default_organizations(apps, schema_editor):
    """
    Crear organizaciones por defecto para usuarios existentes y asignar formularios
    """
    CustomUser = apps.get_model('mainapp', 'CustomUser')
    Organization = apps.get_model('mainapp', 'Organization')
    OrganizationMembership = apps.get_model('mainapp', 'OrganizationMembership')
    DynamicForm = apps.get_model('mainapp', 'DynamicForm')
    
    # Crear organizaciones para cada usuario que tiene formularios
    form_creators = CustomUser.objects.filter(created_forms__isnull=False).distinct()
    
    for user in form_creators:
        # Crear organización para el usuario
        org_name = f"Organización de {user.username}"
        org_slug = slugify(org_name)
        
        # Asegurar que el slug sea único
        counter = 1
        original_slug = org_slug
        while Organization.objects.filter(slug=org_slug).exists():
            org_slug = f"{original_slug}-{counter}"
            counter += 1
        
        organization = Organization.objects.create(
            name=org_name,
            description=f"Organización personal de {user.username}",
            owner=user,
            slug=org_slug,
            is_active=True
        )
        
        # Crear membresía del propietario
        OrganizationMembership.objects.create(
            user=user,
            organization=organization,
            role='owner',
            is_active=True
        )
        
        # Asignar todos los formularios del usuario a su organización
        user_forms = DynamicForm.objects.filter(creator=user, organization__isnull=True)
        for form in user_forms:
            form.organization = organization
            form.save()
    
    # Crear organización por defecto para usuarios sin formularios
    users_without_forms = CustomUser.objects.exclude(id__in=form_creators.values_list('id', flat=True))
    
    if users_without_forms.exists():
        # Crear una organización por defecto
        default_org, created = Organization.objects.get_or_create(
            slug='organizacion-por-defecto',
            defaults={
                'name': 'Organización por Defecto',
                'description': 'Organización temporal para usuarios existentes',
                'owner': users_without_forms.first(),
                'is_active': True
            }
        )
        
        # Crear membresías para todos los usuarios sin organización
        for user in users_without_forms:
            if not OrganizationMembership.objects.filter(user=user).exists():
                role = 'owner' if user == default_org.owner else 'admin'
                OrganizationMembership.objects.create(
                    user=user,
                    organization=default_org,
                    role=role,
                    is_active=True
                )


def reverse_organizations(apps, schema_editor):
    """
    Revertir la creación de organizaciones
    """
    Organization = apps.get_model('mainapp', 'Organization')
    OrganizationMembership = apps.get_model('mainapp', 'OrganizationMembership')
    
    # Eliminar todas las membresías y organizaciones
    OrganizationMembership.objects.all().delete()
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_add_organizations'),
    ]

    operations = [
        migrations.RunPython(
            create_default_organizations,
            reverse_organizations,
        ),
    ]
