# Generated by Django 5.1.7 on 2025-08-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_populate_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='mainapp.organization'),
        ),
    ]
