# Generated by Django 5.2.4 on 2025-08-07 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_make_organization_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLogicProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_type', models.CharField(choices=[('inventory', 'Gestión de Inventario'), ('sales', 'Procesamiento de Ventas'), ('calculations', 'Cálculos Automáticos'), ('notifications', 'Notificaciones'), ('custom', 'Lógica Personalizada')], max_length=50)),
                ('config_data', models.JSONField(default=dict, verbose_name='Configuración')),
                ('python_code', models.TextField(blank=True, verbose_name='Código Python personalizado')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_logic', to='mainapp.dynamicform')),
            ],
            options={
                'verbose_name': 'Lógica de Negocio',
                'verbose_name_plural': 'Lógicas de Negocio',
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('inventory', 'Inventario'), ('sales', 'Ventas'), ('hr', 'Recursos Humanos'), ('customer', 'Atención al Cliente'), ('finance', 'Finanzas'), ('general', 'General')], max_length=20, verbose_name='Categoría')),
                ('icon', models.CharField(default='fas fa-file-alt', max_length=50, verbose_name='Icono Font Awesome')),
                ('template_data', models.JSONField(verbose_name='Datos de la plantilla')),
                ('business_logic', models.TextField(blank=True, verbose_name='Lógica de negocio (Python)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Formulario',
                'verbose_name_plural': 'Plantillas de Formularios',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del artículo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU/Código')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock mínimo')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='mainapp.organization')),
            ],
            options={
                'verbose_name': 'Artículo de Inventario',
                'verbose_name_plural': 'Artículos de Inventario',
                'ordering': ['name'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('adjustment', 'Ajuste'), ('return', 'Devolución')], max_length=20)),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='mainapp.organization')),
                ('related_form_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.formsubmission', verbose_name='Envío de formulario relacionado')),
            ],
            options={
                'verbose_name': 'Transacción de Inventario',
                'verbose_name_plural': 'Transacciones de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
