# Generated by Django 5.1.7 on 2025-08-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_add_templates_and_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformfield',
            name='allowed_file_types',
            field=models.CharField(blank=True, default='image/*,application/pdf,.doc,.docx,.txt', help_text='Tipos de archivo permitidos separados por comas (ej: image/*,application/pdf,.txt)', max_length=500),
        ),
        migrations.AddField(
            model_name='dynamicformfield',
            name='file_cost_per_mb',
            field=models.FloatField(blank=True, default=1.0, help_text='Costo en monedas por MB de archivo subido', null=True),
        ),
        migrations.AddField(
            model_name='dynamicformfield',
            name='max_file_size_mb',
            field=models.FloatField(blank=True, default=5.0, help_text='Tamaño máximo del archivo en MB (por defecto 5 MB)', null=True),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('cost_charged', models.PositiveIntegerField(default=0, help_text='Monedas cobradas por este archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dynamicformfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mainapp.formsubmission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
